### ISSUE TITLE
Start/play button not enabled when text input starts with tag

### ISSUE THREAD

**Issue by lightonflux** [lakoliu/Furtherance#120]
Text input with message + tag:

![Bildschirmfoto vom 2023-10-17 11-47-21](https://github.com/lakoliu/Furtherance/assets/1377943/173b4512-6640-4200-9fd6-64cf9622b4bd)

Text input with tag + message:
![Bildschirmfoto vom 2023-10-17 11-47-10](https://github.com/lakoliu/Furtherance/assets/1377943/8499bb9d-6b34-4dec-96e1-b0ef974b19bf)

If you use tags as projects, then it might feel more natural to write down the tag/project first, and then what you are working on. Sadly this does not work with 1.8.2.

**Comment by lakoliu** [comment]
This is the expected behavior and has always been the case with Furtherance. Tags can be multiple words, so in your second example, "tag test message" is the tag. Furtherance wouldn't know where you want your tag to end and your task name to start. Therefore, the task needs to always start with the task name and then you can add tags if you want them.
