### ISSUE TITLE
Cut-off scrollview at the bottom

### ISSUE THREAD

**Issue by bertob** [lakoliu/Furtherance#3]
When scrolling there's a weird cutoff at the bottom of the window:

![image](https://user-images.githubusercontent.com/1908896/160942243-3c70f779-6532-40da-873f-a126f8c3b3bc.png)

**Comment by lakoliu** [comment]
Again, thank you @bertob for all the great feedback. I've now fixed this in commit f8d10ba. Originally I added it because I thought the UI looked better with the same border on all sides, but now I can see that it may seem strange. It will now go to the bottom of the app window:
![Screenshot from 2022-03-31 10-06-50](https://user-images.githubusercontent.com/99976966/161008279-45a2b991-5d35-48f6-aae2-8d7cc2d298f2.png)
