### ISSUE TITLE
[Wayland] Gdk-Message: Error flushing display: Protocol error

### ISSUE THREAD

**Issue by gapplef** [lakoliu/Furtherance#60]
Ubuntu 22.04 + Gnome 42.1 + NVIDIA GeForce 940MX

After compiled from source, furtherance can't start under wayland: `Gdk-Message: Error flushing display: Protocol error`
The problems can be fixed with set `GDK_BACKEND=x11`, so it should relate to wayland (and NVIDIA)

Similar issues I have encountered for other apps (may or may not helpful)
- https://github.com/mjakeman/extension-manager/issues/184
- https://github.com/mpv-player/mpv/issues/10152
- https://github.com/kovidgoyal/kitty/issues/4878

**Comment by lakoliu** [comment]
This is interesting because I created Furtherance on a computer using Wayland and an NVIDIA card and haven't had any issues. I've looked into those links you sent and it looks like some people have this issue and others don't. It seems like it could be an overall issue with GTK 4 and libadwaita. I don't think there is anything I can do to resolve it for now. If anyone else is facing this issue (or is using NVIDIA and Wayland and _not_ having any issues), please let us know.

**Comment by BlackJohnny** [comment]
I am using Ubuntu 22.04 + Gnome 42.2 + Nvidia GTX 1650 Ti on Wayland and i get the same error:
```
Gdk-Message: 22:24:18.440: Error flushing display: Protocol error
```

**Comment by BlackJohnny** [comment]
> I am using Ubuntu 22.04 + Gnome 42.2 + Nvidia GTX 1650 Ti on Wayland and i get the same error:
> 
> ```
> Gdk-Message: 22:24:18.440: Error flushing display: Protocol error
> ```
> 
> and the `GDK_BACKEND=x11` avoids the issue

Actually the env variable only allows it to open the main window ... the rest of the functionality is broken

**Comment by lakoliu** [comment]
This is very strange. I also have an Nvidia GTX 1650 Ti. Are you running it in a container or VM? If not, did you install Furtherance via Flathub?

**Comment by mkrupczak3** [comment]
Same issue with a different, also on a laptop with a 940MX. Appears to be an issue with Wayland. Might be device errata, coincidence is to great to discount this possibility

**Comment by lakoliu** [comment]
@mkrupczak3 did you install Furtherance via Flatpak/Flathub?
