### ISSUE TITLE
MacOS port

### ISSUE THREAD

**Issue by skhoroshavin** [lakoliu/Furtherance#75]
Absolutely love this app, the only thing that makes me upset about it  is that it doesn't have a MacOS port. Any chance of making it possible?

**Comment by lakoliu** [comment]
Yes! I really want to create a native Mac app using SwiftUI, but I don't have a Mac, so unfortunately it will probably be quite a while 😔.

**Comment by skhoroshavin** [comment]
Awesome! Do you have any plans regarding keeping some common code, or you envisioned this as a complete rewrite? Also while I cannot make any commitments right now I really hope to get out of crunch in about 1-2 months (right now I'm changing job and moving my family to another country😓), and I'd be interested in at least trying to provide some dev help while learning SwiftUI in process.

**Comment by lakoliu** [comment]
It will be a complete rewrite because, like Furtherance for Windows, it will most likely not be open-source and will only be available for about $4.99 from the app store. I'm using the Windows and eventual Mac apps as a way to earn a little bit to support the development of Furtherance as a whole. Therefore, unfortunately, I won't be able to accept any help, though I greatly appreciate the offer. 

For now though, you may be able to compile Furtherance on Mac. It should work just fine, it just won't have idle detection. But I haven't tried it yet since I don't have a Mac, so I'm not sure what issues you may run into, if any. 

Thanks again, and let me know if you get it working on Mac! And good luck with the move! I've moved to another country, but not with a family, so I can only imagine how much work that must be.

**Comment by lakoliu** [comment]
Just a little update: I got a Mac so I've been working on creating Furtherance for Mac in SwiftUI. I'm hoping it will be done in the next month or two! Could be a little longer though. Thanks for being patient!

**Comment by lakoliu** [comment]
The Mac version of Furtherance is finally out! I decided to make it free, but there are two features (idle detection and reports) that require an in-app purchase. You should be able to find it in the Mac App Store now, or use [this link](https://apps.apple.com/app/furtherance/id1659277200).

Thank you for being patient while I worked on this, and if you like it I'd really appreciate it if you leave a review to help promote it in the App Store! (If you don't like it, let me know and I'll try to make it better! 😂)
