### ISSUE TITLE
Costs money on Play Store

### ISSUE THREAD

**Issue by codeBodger** [lakoliu/Furtherance#98]
I was just wondering why this __open source__ program costs money on Google Play Store.  If I'm missing something, just let me know.

**Comment by lakoliu** [comment]
Furtherance for Android uses a different code base (it's created with Flutter) and does cost on the Google Play Store. Only the Linux version of Furtherance is currently free and open-source. I use the proceeds from other platforms to fund development (though the proceeds at this point are shockingly small). 

Furtherance was written with C# + WinUI for Windows, Flutter for Android (and soon iOS), and Rust + GTK4 for Linux. Therefore, I have a lot of code to maintain and change every time I add a feature, and I have limited time to do this since I do it in my free time. That is why I charge a small amount for the other versions.
